language: php

services:
  - postgresql

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: LARAVEL_VERSION=8.*
    - php: 7.4
      env: LARAVEL_VERSION=8.*

sudo: false

dist: xenial

env:
  global:
    - setup=basic
    - xdebug=false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $xdebug = 'true' ]] ; then phpenv config-rm xdebug.ini; fi
  - composer self-update --2

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable --prefer-lowest; fi

before_script:
  - travis_retry composer install --prefer-source --no-interaction
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/framework:${LARAVEL_VERSION}" --no-update; fi;
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "illuminate/support:${LARAVEL_VERSION}" --no-update; fi;
  - composer update
  - cp -f phpunit.xml.travis phpunit.xml
  - psql -c 'create database travis_ci_test;' -U postgres


script:
  - composer test
